# Spring Boot configuration
spring:
  application:
    name: employee-service
    #main:
    # allow-bean-definition-overriding: true
    # lazy-initialization: true
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hl_enterprise
    username: postgres
    password: 1234
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true

  # spring mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: maxim.gorodnyk55@gmail.com
    password: bqfwqrjoyvderwfp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    #    locations: filesystem:.\src\main\resources\db\migration
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
#  security:
#    user:
#      name: admin
#      password: admin
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    #org.hibernate: debug
    com.example.demowithtests: debug
# Server configuration
server:
  port: 8088 #set your port
# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html # swagger-ui custom path
  api-docs:
    path: /v3/api-docs.yaml
management: # spring actuator
  endpoints:
    #enabled-by-default: true # If changed to false, you can enable separate functionality as indicated below
  #endpoint: # here
   # health:
    #  enabled: true
    web:
      exposure:
       # exclude: "*"
        include: "*"


